import type { NextPage } from "next";
import Head from "next/head";
import chip from "../public/chip.png";
import Image from "next/image";
import { useState } from "react";

const Home: NextPage = () => {
    const elements = ["Rotate", "Fade", "Squich and Stretch", "Move"];
    const [rotate, setRotate] = useState(false);
    const [fade, setFade] = useState(false);
    const [squich, setSquich] = useState(false);
    const [move, setMove] = useState(false);
    const startAnimation = (e: React.MouseEvent<HTMLElement>) => {
        //@ts-ignore
        const elementID = e.target.id;
        if (elementID === "Rotate") {
            setRotate(!rotate);
        }
        if (elementID === "Fade") {
            setFade(!fade);
        }
        if (elementID === "Squich and Stretch") {
            setSquich(!squich);
        }
        if (elementID === "Move") {
            setMove(!move);
        }
    };
    return (
        <div className="h-screen w-screen overflow-auto">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="absolute flex list-none justify-center w-screen bg-gray-200 p-4 space-x-20">
                {elements.map((element, id) => {
                    return (
                        <button
                            key={id}
                            id={element}
                            onClick={(e) => startAnimation(e)}
                        >
                            {element}
                        </button>
                    );
                })}
            </div>

            {move && (
                <div className="flex justify-center items-center h-full w-full ">
                    <Image
                        src={chip}
                        width="200px"
                        height="200px"
                        className="animate-spin"
                    />
                </div>
            )}
            {fade && (
                <div className="flex justify-center items-center h-full w-full ">
                    <Image
                        src={chip}
                        width="200px"
                        height="200px"
                        className="animate-pulse"
                    />
                </div>
            )}
            {rotate && (
                <div className="flex justify-center items-center h-full w-full ">
                    <Image
                        src={chip}
                        width="200px"
                        height="200px"
                        className="animate-spin"
                    />
                </div>
            )}
            {squich &&
                <div className="flex justify-center items-center h-full w-full ">
                    <Image
                        src={chip}
                        width="200px"
                        height="200px"
                        className="animate-bounce"
                    />
                </div>
            }
			{!squich && !move && !rotate && !fade &&

                <div className="flex justify-center items-center h-full w-full ">
                    <Image
                        src={chip}
                        width="200px"
                        height="200px"
                    />
                </div>
			}
        </div>
    );
};

export default Home;
